name: Deploy

on: [push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Test backend
        working-directory: ./astra-api
        run: ./gradlew test
