name: Testing

on: [push]

jobs:
  unit_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Test backend
        working-directory: ./astra-api
        run: ./gradlew test
  integration_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Integration test backend
        working-directory: ./astra-api
        run: ./gradlew integrationTest
